Tachzukanit/TachzukanitBE/Models/Malfunction.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TachzukanitBE.Models
{
    public class Malfunction
    {
        #region Properties

        public string MalfunctionId { get; set; }

        public Status Status { get; set; }

        [Required]
        [MinLength(4)]
        [MaxLength(25)]
        public string Title { get; set; }

        [Required]
        [MinLength(4)]
        [MaxLength(200)]
        public string Content { get; set; }

        [DisplayName("Photo")]
        public string Resources { get; set; }

        [DisplayName("Creation Date")]
        [DataType(DataType.Date)]
        public DateTime CreationDate { get; set; }

        [DisplayName("Modification Date")]
        [DataType(DataType.Date)]
        public DateTime ModifiedDate { get; set; }

        [DisplayName("Apartment")]
        public Apartment CurrentApartment { get; set; }

        [DisplayName("Requested By")]
        public User RequestedBy { get; set; }

        #endregion
    }
}

Tachzukanit/TachzukanitBE/Controllers/MalfunctionsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.NodeServices;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using TachzukanitBE.Data;
using TachzukanitBE.Models;
using TachzukanitBE.Services;
using TachzukanitBE.ViewModels;

namespace TachzukanitBE.Controllers
{
    public class MalfunctionsController : Controller
    {
        private readonly TachzukanitDbContext _context;
        private readonly IHostingEnvironment he;

        public MalfunctionsController(TachzukanitDbContext context, IHostingEnvironment e)
        {
            _context = context;
            he = e;
        }

        // POST: Get malfunctions parameters from the user and search in server
        //       it shows the malfunctions details and also user name, appartment password
        public async Task<IActionResult> ShowMalfExtraDetails(DateTime createDate, Status status,
                                                              string address, string userName)
        {
            if ((createDate == null) && (String.IsNullOrEmpty(status.ToString())) &&
                  String.IsNullOrEmpty(address) && String.IsNullOrEmpty(userName))
            {
                return View(await _context.Malfunction.ToListAsync());
            }

            return (await SearchMalfExtraDetails(createDate, status, address, userName));
        }

        private async Task<IActionResult> SearchMalfExtraDetails(DateTime createDate, Status status,
                                                              string address, string userName)
        {
            Status enumStatus = (Status)status;

            var q = from malfunction in _context.Malfunction
                    join apartments in _context.Apartment on malfunction.CurrentApartment equals apartments
                    join users in _context.User on malfunction.RequestedBy equals users
                    where malfunction.CreationDate >= createDate &&
                          malfunction.Status.Equals(enumStatus) &&
                          apartments.Address.Equals(address) &&
                          malfunction.RequestedBy.Email.Contains(userName)
                    select new ExtraDetailsMalfunctionsVM()
                    {
                        Title = malfunction.Title,
                        Status = malfunction.Status.ToString(),
                        Content = malfunction.Content,
                        CreationDate = malfunction.CreationDate,
                        ModifiedDate = malfunction.ModifiedDate,
                        AppartmentAddress = apartments.Address,
                        UserName = users.FullName
                    };

             return View(await q.ToListAsync());
    }

        // GET: Malfunctions
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Index(String searchString)
        {
            var databaseContext = _context.Malfunction.Include(p => p.CurrentApartment).Include(ps => ps.RequestedBy);

            if (String.IsNullOrEmpty(searchString))
            {
                return View(await databaseContext.ToListAsync());
            }

            return View(await databaseContext.Where(m => m.Content.Contains(searchString)).ToListAsync());
        }

        // GET: Malfunctions/Details/5
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var malfunction = await _context.Malfunction
                .FirstOrDefaultAsync(m => m.MalfunctionId == id);
            if (malfunction == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(malfunction);
        }

        // GET: Malfunctions/Create
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Create()
        {
            var apartments = from apt in _context.Apartment.Include(s => s.malfunctions)
                             select new { Value = apt.ApartmentId, Text = apt.Address };

            var users = from usr in _context.User.Include(s => s.malfunctions)
                        select new { Value = usr.Id, Text = usr.Email };

            var statuses = from Status stat in Enum.GetValues(typeof(Status))
                           select new { Value = (int)stat, Text = stat.ToString() };

            ViewData["all_appartments"] = new SelectList(await apartments.ToListAsync(), "Value", "Text");
            ViewData["all_users"] = new SelectList(await users.ToListAsync(), "Value", "Text");
            ViewData["statuses"] = new SelectList(statuses, "Value", "Text");

            return View();
        }

        // POST: Malfunctions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Create([Bind("CurrentApartment")]int CurrentApartment, [Bind("RequestedBy")]string RequestedBy, [Bind("MalfunctionId,Status,Title,Content,Resources,CurrentApartmentId,RequestedById")] Malfunction malfunction, IFormFile mFiles)
        {            
            if (ModelState.IsValid)
            {
                // Creating the query of the apartment
                var queryApt = from apt in _context.Apartment
                               where apt.ApartmentId == CurrentApartment
                               select apt;

                // Creating the query of the user
                var queryUsr = from usr in _context.User
                               where usr.Id == RequestedBy
                               select usr;

                // If the id of the apartment/user does not exist in DB
                if (!queryApt.Any() || !queryApt.Any())
                {
                    return View(malfunction);
                }

                // Adding the apartment to the malfunction to save
                var curApartment = queryApt.First();
                malfunction.CurrentApartment = curApartment;
                
                // Adding the user to the malfunction to save
                var curUser = queryUsr.First();
                malfunction.RequestedBy= curUser;

                // Adding the creation date and modification date
                malfunction.CreationDate = DateTime.Now;
                malfunction.ModifiedDate = DateTime.Now;

                // Uploading photo describing the malfunction
                SavePhoto(malfunction, mFiles);

                _context.Add(malfunction);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(malfunction);
        }

        private void SavePhoto(Malfunction malfunction, IFormFile mFiles)
        {
            // Sanity check apartment cant be null
            if (malfunction == null)
            {
                return;
            }

            // If there is no defined photo, set the default photo
            if (mFiles == null)
            {
                malfunction.Resources = "/images/malfunctions/default_malfunction_photo.jpg";
                return;
            }

            var fileName = Path.Combine(he.WebRootPath + "/images/malfunctions", Path.GetFileName(mFiles.FileName));
            malfunction.Resources = "/images/malfunctions/" + mFiles.FileName;

            // If the file does not exist already creating it
            if (!System.IO.File.Exists(fileName))
            {
                mFiles.CopyTo(new FileStream(fileName, FileMode.Create));
            }
        }

        // GET: Malfunctions/Edit/5
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var malfunction = await _context.Malfunction.FindAsync(id);
            if (malfunction == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            // Adding all the statuses to the viewData
            var statuses = from Status stat in Enum.GetValues(typeof(Status))
                select new { Value = (int)stat, Text = stat.ToString() };
            ViewData["statuses"] = new SelectList(statuses, "Value", "Text");

            return View(malfunction);
        }

        // POST: Malfunctions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Janitor,Guide,SocialWorker")]
        public async Task<IActionResult> Edit(string id, [Bind("MalfunctionId,Status,Title,Content,Resources")] Malfunction malfunction, IFormFile files)
        {
            if (id != malfunction.MalfunctionId)
            {
                return RedirectToAction("NotFoundPage");
            }

            if (ModelState.IsValid)
            {
                if (files != null)
                {
                    SavePhoto(malfunction, files);
                }

                if (!MalfunctionExists(malfunction.MalfunctionId))
                    return RedirectToAction("NotFoundPage");

Tachzukanit/TachzukanitBE/Views/Malfunctions/Create.cshtml
@model TachzukanitBE.Models.Malfunction

@{
    ViewData["Title"] = "Create";
}
@section Scripts
    {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <link rel="stylesheet" href="~/css/main.css" />
}

    <div style="float:right">
        <a class="btn btn-default" asp-action="Index">
            <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
    <h2>Create Malfunction</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="ViewBag.statuses"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resources" class="control-label"></label>
                <input type="file" name="mFiles" />
            </div>
            <div class="form-group">
                <label asp-for="CurrentApartment" class="control-label"></label>
                <select asp-for="CurrentApartment" class="form-control" asp-items="ViewBag.all_appartments" }></select>
                <span asp-validation-for="CurrentApartment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequestedBy" class="control-label"></label>
                <select asp-for="RequestedBy" class="form-control" asp-items="ViewBag.all_users" }></select>
                <span asp-validation-for="RequestedBy" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <Button type="submit" class="btn btn-success">Create</Button>
            </div>
        </form>
    </div>
</div>

Tachzukanit/TachzukanitBE/Views/Malfunctions/Delete.cshtml
@model TachzukanitBE.Models.Malfunction

@{
    ViewData["Title"] = "Delete";
}
@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(
            $(function () {
                $("#dialog-delete").dialog({
                    autoOpen: false,
                    show: {
                        effect: "blind",
                        duration: 1000
                    },
                    hide: {
                        effect: "explode",
                        duration: 1000
                    },
                    buttons: {
                        "Yes": function () {
                            $('#delete-form').submit();
                        },
                        No: function () {
                            $(this).dialog("close");
                        }
                    }
                });

                $('[data-confirm]').click(function (e) {
                    $("#dialog-delete").dialog("open");
                });
            }));
    </script>
}
<div style="float:right">
    <a class="btn btn-default" asp-action="Index">
        <i class="fa fa-arrow-left"></i> Back
    </a>
</div>
<h2>Delete Malfunction</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Resources)
        </dt>
        <dd>
            <img class="img-large" src="@Url.Content(Model.Resources)" alt="" style="width:200px;height:200px;"/>
        </dd>
    </dl>

    <form asp-action="Delete" id="delete-form">
        <input type="hidden" asp-for="MalfunctionId" />
        <Button type="button" class="btn btn-danger" data-confirm="Are you sure?" value="Yes">
            <i class="fa fa-trash-o fa-lg"></i> Delete
        </Button>
    </form>
    <div id="dialog-delete" title="Delete" class="dialog-message">
        <p>Are you sure?</p>
    </div>
</div>

Tachzukanit/TachzukanitBE/Views/Malfunctions/Details.cshtml
@model TachzukanitBE.Models.Malfunction

@{
    ViewData["Title"] = "Details";
}

@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
}

    <div style="float:right">
        <a class="btn btn-default" asp-action="Index">
            <i class="fa fa-arrow-left"></i> Back
        </a> |
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.MalfunctionId">
            <i class="fa fa-edit"></i> Edit
        </a> |
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.MalfunctionId">
            <i class="fa fa-trash-o fa-lg"></i> Delete
        </a>
    </div>

    <h2>Malfunction Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Resources)
        </dt>
        <dd>
            <img class="img-large" src="@Url.Content(Model.Resources)" alt="" style="width:300px;height:300px;"/>
        </dd>
    </dl>
</div>

Tachzukanit/TachzukanitBE/Views/Malfunctions/Edit.cshtml
@model TachzukanitBE.Models.Malfunction

@{
    ViewData["Title"] = "Edit";
}
@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

    <div style="float:right">
        <a class="btn btn-default" asp-action="Index">
            <i class="fa fa-arrow-left"></i> Back
        </a>
    </div>
<h2>Edit Malfunction</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MalfunctionId" />
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="ViewBag.statuses"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Resources" class="control-label"></label>
                <input asp-for="Resources" class="form-control" type="hidden" />
                <img class="img-large" src="@Url.Content(Model.Resources)" alt="" style="width:200px;height:200px;"/>
                <div class="form-group">
                    <input type="file" name="files" />
                </div>
                <span asp-validation-for="Resources" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <Button type="submit" class="btn btn-success">Save</Button>
            </div>
        </form>
    </div>
</div>

Tachzukanit/TachzukanitBE/Views/Malfunctions/Index.cshtml
@model IEnumerable<TachzukanitBE.Models.Malfunction>

@{
    ViewData["Title"] = "Index";
}

@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/search.css" />
}

<h2>Malfunctions</h2>


<form asp-controller="Malfunctions" asp-action="Index" method="get">
    <div class="search">
        <input name="SearchString" type="text" class="search-query" placeholder="Search" />
        <button id="searchButton" class="search-button" type="submit">
            <i class="fa fa-search"></i>
        </button>
    </div>
</form>

<a class="btn btn-success" asp-action="Create">
    <i class="fa fa-plus fa-2x"></i> Add
</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Resources)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentApartment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestedBy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    <img class="img-large" src="@Url.Content(item.Resources)" alt="" style="width:100px;height:100px;"/>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentApartment.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestedBy.Email)
                </td>
                <td>
                    <br>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.MalfunctionId">
                        <i class="fa fa-edit"></i>
                    </a>
                    <br>
                    <br>
                    <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.MalfunctionId">
                        <i class="fa fa-info"></i>
                    </a>
                    <br>
                    <br>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.MalfunctionId">
                        <i class="fa fa-trash-o fa-lg"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Tachzukanit/TachzukanitBE/Views/Malfunctions/NotFoundPage.cshtml
@{
    ViewData["Title"] = "NotFound";
}

@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
}

<h2>This Page Could Not Be Found At This Moment</h2>
<p>This error may occur if you tried to edit a page that already been deleted or entered to an non-existing address</p>

Tachzukanit/TachzukanitBE/Views/Malfunctions/ShowMalfExtraDetails.cshtml
@model IEnumerable<TachzukanitBE.ViewModels.ExtraDetailsMalfunctionsVM>

@{
    ViewData["Title"] = "Manager Screen";
}
@section Scripts
    {
    <link rel="stylesheet" href="~/css/main.css" />
}

<h2>Manager Screen</h2>
<br />

<form asp-controller="Malfunctions" asp-action="ShowMalfExtraDetails" method="get">
    <div class="search" style="display:flex; width:100%">
        <p>Date: <input name="createDate" type="datetime-local" class="search-query" style="padding-right:4%;margin-right:4%" /></p>
      @Html.DropDownList("Status", new List<SelectListItem> { new SelectListItem { Value ="Open" , Text ="Open" },
                            new SelectListItem { Value = "Closed" , Text ="Closed" },
                            new SelectListItem { Value = "InProgress" , Text ="In Progress" }}, "Please choose status")
        <input name="address" type="text" class="search-query" placeholder="Search Address" style="margin-left:3%;padding-left:4%" />
        <input name="userName" type="text" class="search-query" placeholder="Search Name" style="margin-left:3%; margin-right:4%" />
        <button id="searchButton" class="search-button" type="submit">
            <i class="fa fa-search"></i>
        </button>
    </div>
</form>


<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppartmentAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AppartmentAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
            </tr>
        }
    </tbody>
</table>