Tachzukanit/TachzukanitBE/Controllers/ApartmentsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GoogleMaps.LocationServices;
using GuigleAPI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TachzukanitBE.Data;
using TachzukanitBE.Models;
using System.Net;
using ProtoBuf;
using transit_realtime;


namespace TachzukanitBE.Controllers
{
    public class ApartmentsController : Controller
    {
        private readonly TachzukanitDbContext _context;
        private readonly IHostingEnvironment he;


        public ApartmentsController(TachzukanitDbContext context, IHostingEnvironment e)
        {
            _context = context;
            he = e;
        }

        // GET: Apartments
        public async Task<IActionResult> Index(String searchString)
        {
            if (String.IsNullOrEmpty(searchString))
            {
                return View(await _context.Apartment.ToListAsync());
            }

            return View(await _context.Apartment.Where(a => a.Address.Contains(searchString)).ToListAsync());
        }

        // GET: Apartments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var apartment = await _context.Apartment.Include(x=> x.malfunctions)
                .FirstOrDefaultAsync(m => m.ApartmentId == id);

            if (apartment == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(apartment);
        }

        // GET: Apartments/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Apartments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ApartmentId,Address,Photo,RoomsNumber")] Apartment apartment, IFormFile files)
        {
            if (ModelState.IsValid)
            {
                // Getting the long lat
                var location = AddLongLatAsync(apartment.Address);
                apartment.Latitude = location.Result.Latitude;
                apartment.Longitude = location.Result.Longitude;
                SavePhoto(apartment, files);
                _context.Add(apartment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(apartment);
        }

        private async Task<MapPoint> AddLongLatAsync(string apartmentAddress)
        {
            MapPoint point;

            // Getting the location of the address
            try
            {
                GoogleGeocodingAPI.GoogleAPIKey = "AIzaSyDKp42W_7Sc_kcVimZm-pPKG2TCXeFdzto";
                var result = await GoogleGeocodingAPI.GetCoordinatesFromAddressAsync(apartmentAddress);
                point = new MapPoint
                {
                    Latitude = result.Item1,
                    Longitude = result.Item2
                };


            }
            catch (Exception ex)
            {
                point = new MapPoint
                {
                    Latitude = 32.1637206,
                    Longitude = 34.8647352
                };
            }

            return point;
        }

        private void SavePhoto(Apartment apartment, IFormFile files)
        {
            // Sanity check apartment cant be null
            if (apartment == null)
            {
                return;
            }

            // If there is no defined photo, set the default photo
            if (files == null)
            {
                apartment.Photo = "/images/apartments/default_photo.jpg";
                return;
            }

            var fileName = Path.Combine(he.WebRootPath + "/images/apartments", Path.GetFileName(files.FileName));
            apartment.Photo = "/images/apartments/" + files.FileName;

            // If the file does not exist already creating it
            if (!System.IO.File.Exists(fileName))
            {
                files.CopyTo(new FileStream(fileName, FileMode.Create));
            }
        }

        // GET: Apartments/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var apartment = await _context.Apartment.FindAsync(id);
            if (apartment == null)
            {
                return RedirectToAction("NotFoundPage");
            }
            return View(apartment);
        }

        // POST: Apartments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ApartmentId,Address,Photo,RoomsNumber")] Apartment apartment, IFormFile files)
        {
            if (id != apartment.ApartmentId)
            {
                return RedirectToAction("NotFoundPage");
            }

            if (ModelState.IsValid)
            {
                if (files != null)
                {
                    SavePhoto(apartment, files);
                }

                try
                {
                    _context.Update(apartment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApartmentExists(apartment.ApartmentId))
                    {
                        return RedirectToAction("NotFoundPage");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(apartment);
        }

        // GET: Apartments/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            var apartment = await _context.Apartment
                .FirstOrDefaultAsync(m => m.ApartmentId == id);
            if (apartment == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(apartment);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var apartment = await _context.Apartment.FindAsync(id);
            _context.Apartment.Remove(apartment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApartmentExists(int id)
        {
            return _context.Apartment.Any(e => e.ApartmentId == id);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult NotFoundPage()
        {
            return View();
        }
    }
}

Tachzukanit/TachzukanitBE/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TachzukanitBE.Data;
using Microsoft.AspNetCore.Authorization;
using TachzukanitBE.Models;
using Microsoft.AspNetCore.Identity;

namespace TachzukanitBE.Controllers
{
    public class UsersController : Controller
    {
        private readonly TachzukanitDbContext _context;
        private readonly UserManager<User> _userManager;

        public UsersController(TachzukanitDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private async Task<IActionResult> SearchUserDetails(string Name, string Email, string Address)
        {
            var q = from users in _context.User
                    where users.FullName.Contains(Name) &&
                          users.Email.Contains(Email) &&
                          users.Address.Contains(Address)
                    select users;

            return View(await q.ToListAsync());
        }

            public async Task<IActionResult> Index(string Name, string Email, string Address)
        {
            if (String.IsNullOrEmpty(Name) && String.IsNullOrEmpty(Email) && String.IsNullOrEmpty(Address))
            {
                return View(await _context.User.ToListAsync());
            }

            return (await SearchUserDetails(Name, Email, Address));
        }

        public async Task<IActionResult> Details(String id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return RedirectToAction("NotFoundPage");
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id.ToString());

            if (user == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(user);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(String id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return RedirectToAction("NotFoundPage");
            }
            if (_userManager.GetUserId(HttpContext.User).Equals(id))
            {
                return Redirect("/Identity/Account/Manage");
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return RedirectToAction("NotFoundPage");
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(String id, [Bind("Id,FullName,Email,PhoneNumber,Address")] User user)
        {
            if (!id.Equals(user.Id))
            {
                return RedirectToAction("NotFoundPage");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    User dbUser = (User)_context.Users.First(u => u.Id == id);
                    dbUser.PhoneNumber = user.PhoneNumber;
                    dbUser.FullName = user.FullName;
                    dbUser.Address = user.Address;
                    _context.Update(dbUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return RedirectToAction("NotFoundPage");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(user);
        }

        private bool UserExists(String id)
        {
            return _context.User.Any(e => e.Id == id);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(String id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return RedirectToAction("NotFoundPage");
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return RedirectToAction("NotFoundPage");
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(String id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult NotFoundPage()
        {
            return View();
        }
    }

}

Tachzukanit/TachzukanitBE/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TachzukanitBE</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/main.css" />
        <link rel="stylesheet" href="~/css/Navbar-Dropdown.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <div id="dialog" title="Welcome!" class="dialog-message">
        <p>This site created by Karin Wasenstein, Dana Koren, Yoantan Ben Avraham and Stas Fainberg. Please register first!</p>
    </div>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Apartments" asp-action="Index" class="navbar-brand">TachzukanitBE</a>
            </div>
            <div class="navbar-collapse collapse">
                <div class="myDropdown_navbar">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                        <li><a asp-area="" asp-controller="Malfunctions" asp-action="Index">Malfunctions</a></li>
                        <li><a asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a></li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li><a asp-area="" asp-controller="Malfunctions" asp-action="ShowMalfExtraDetails">Manager</a></li>
                        }
                        <li><a asp-area="" asp-controller="Apartments" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Apartments" asp-action="Contact">Contact</a></li>
                        <li>
                            <a id="help">?</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </nav>

    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-text">
                        <span class="name" style="color:white">Ekstein House</span>
                        <span class="skills" style="color:white">Habitation is right here</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="width:100%">

            <aside style="width:40%">
                <p>
                    <iframe scrolling="no" frameborder="0" clocktype="html5" style="overflow:hidden;border:0;margin:0;padding:0;width:450px;height:165px;" src="https://www.clocklink.com/html5embed.php?clock=044&timezone=IST&color=white&size=450&Title=&Message=&Target=&From=2018,1,1,0,0,0&Color=white"></iframe>
                </p>
            </aside>

            <div style="width:60%">
                <p>
                    <div class="fb-share-button"
                         data-href="https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/sharer/sharer.php"
                         data-layout="button_count">
                    </div>
                </p>
                <p>&copy; 2018 - TachzukanitBE</p>
            </div>
        </footer>
    </div>


    <environment include="Development">
        <script src="https://d3js.org/d3.v5.min.js" charset="utf-8"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDKp42W_7Sc_kcVimZm-pPKG2TCXeFdzto&callback=initMap">
        </script>

    </environment>
    <environment exclude="Development">
        <script src="https://d3js.org/d3.v5.min.js" charset="utf-8"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDKp42W_7Sc_kcVimZm-pPKG2TCXeFdzto&callback=initMap">
        </script>
    </environment>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(
            $(function () {
                $("#dialog").dialog({
                    autoOpen: false,
                    show: {
                        effect: "blind",
                        duration: 1000
                    },
                    hide: {
                        effect: "explode",
                        duration: 1000
                    }
                });

                $("#help").click(function () {
                    $("#dialog").dialog("open");
                });
            }));
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>